[modbus]
host = "192.168.178.176"
port = 502
offset = 0
byteorder = "big"

[tedge]
mqtt.host = "localhost"
mqtt.port = 1883

[logging]
level = "DEBUG"

[core]
loop.interval = 10
default.interval = 60
align_timestamps = true

[csv]
header = 0
delimiter = ","
quote = '"'

[registers]
number = ["Register", "Number"]
size = ["Size", "Word", "Length"]
type = ["Type", "Format"]
uom = ["UOM", "Unit"]
min = ["Min", "Val"]
max = ["Max"]
description = ["Desc", "De", "Ger", "En", "Fr"]
tag = ["Tag", "Target", "Map"]
group = ["Group", "Dev", "Set", "Target"]