[modbus]
host = "192.168.178.176"
port = 502
offset = 0
byteorder = "big"

[mqtt]
host = "localhost"
port = 1883

[logging]
level = "INFO"

[core]
loop.interval = 10
default.interval = 60
align_timestamps = true

[csv]
header = 0
delimiter = ","
quote = '"'
